package com.post.test.repository;

import com.post.test.entity.Student;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

// Q10: Derived query methods generated by Spring Data JPA from method names.
public interface StudentRepository extends JpaRepository<Student, Long> {

    List<Student> findByCity(String city);

    List<Student> findByNameAndCity(String name, String city);

    List<Student> findByEmailContaining(String emailText);

    long countByCity(String city);
}
